
# Project
site_name: ModernUO
site_author: Kamron Batman
site_url: https://modernuo.com
edit_uri: edit/main/docs/

# Repository
repo_name: modernuo/modernuo
repo_url: https://github.com/modernuo/modernuo
site_description: The Ultima Online Server Emulator for the modern era!
copyright: Copyright 2019-2023 ModernUO Development Team
theme:
  name: material
  favicon: branding/favicon.png
  icon:
    logo: modernuo/logo
  custom_dir: docs/overrides/
  features:
    - tabs
    - instant
extra_css:
  - assets/stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://muo.gg/github
      name: ModernUO on Github
    - icon: fontawesome/brands/discord
      link: https://muo.gg/discord
      name: ModernUO on Discord
    - icon: fontawesome/brands/patreon
      link: https://muo.gg/patreon
      name: Sponsor ModernUO on Patreon
    - icon: fontawesome/brands/reddit
      link: https://muo.gg/reddit
      name: /r/modernuo
    - icon: fontawesome/brands/twitter
      link: https://muo.gg/twitter
      name: "@modernuo"
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      toc_depth: "1-1"
      permalink: true
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons

# Pages
nav:
  - Home: 'index.md'
  - 'Get Started':
    - 'installation.md'
    - 'building-server.md'
    - 'starting-server.md'
  - 'Scripting guide':
      - 'scripting-guide/timers.md'
      - 'scripting-guide/serialization.md'
